### PR TITLE
@Montycarlos patch 1

### PR DESCRIPTION
**Pull request by montycarlos**
.github/workflows/documentation.yml

### CODE REVIEW

**Comment by michaeljones** [comment]
Can you explain what is going on here?

**Comment by michaeljones** [comment]
I'm going to close it as it looks a bit odd but you can reopen and explain if you like.

**Comment by montycarlos** [comment]
Ok thanks

**Comment by montycarlos** [comment]
But can you explain me what to fix cus I'm really starting

**Comment by michaeljones** [comment]
Hi, generally speaking you would use Breathe and then come to us with an issue that needs fixing if you then want to work on it you would submit a pull request with the necessary changes. I'm afraid I'm not sure what stage you are at but it seems like you are very new to this. I think it is great for anyone to get into programming and open source but I'm not in a place to offer help at the moment. You might want to try YouTube for various instructional videos. Sorry not to be more helpful.

**Pull request closed without merging**
